### ISSUE TITLE
Execution Error when Running Sample Data

### ISSUE THREAD

**Issue by jonLicari** [jonLicari/finance-report#21]
# Description
- error occurs when running the sample dataset

```
Selecting sample dataset
Utilities total = $4800.0
  Rent: $4800.0
Food total = $722.0
  Grocery: $542.0
  Restaurant: $180.0
Career total = $1860.0
  nan: $1860.0
Transportation total = $120.0
  Gas: $120.0
Shopping total = $450.0
  Other: $450.0
Income total = $2400.0
  Salary: $2400.0
Traceback (most recent call last):
  File "..././finreport_main.py", line 367, in <module>
    main()
  File "..././finreport_main.py", line 363, in main
    categorical_total(refined_data)
  File "..././finreport_main.py", line 165, in categorical_total
    create_report(expense_list)
  File "..././finreport_main.py", line 178, in create_report
    fig1 = plot_net_savings(expense_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..././finreport_main.py", line 330, in plot_net_savings
    savings_percent = round((total_savings / total_income) * 100, 2)
                             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

**Comment by jonLicari** [comment]
# Update
While addressing a different issue, I found that one of the reasons for this issue is that the sample data income was lower than the total expenditures. This was then causing issues calculating percentages for savings, breaking the program.

# Sol'n
- [ ] Create a PR to fine-tune the Sample data so that it can resemble sensible expense trends.
- [ ] add better handling for mathematical edge cases
- [ ] fix whatever is causing the plots to to not show up
